<?php

namespace Database\Seeders;

use App\Models\Post;
use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $posts = [
            [
                'title' => 'The Science of Ionized Alkaline Water: Cellular Hydration Explained',
                'slug' => 'science-of-ionized-alkaline-water',
                'category' => 'Hydration & Health',
                'author_name' => 'Dr. R. Sharma (Biophysicist)',
                'excerpt' => 'How negative oxidation reduction potential (ORP) and micro-clustered water molecules accelerate cellular recovery and reduce physiological acidity.',
                'content' => '<h2>Understanding Alkaline Water Beyond the Hype</h2>
<p>Alkaline water has moved from a fitness trend into a verified scientific staple for athletes, executives, and health-conscious families. But what makes ionized alkaline water functionally distinct from regular water?</p>
<h3>1. Optimum pH Balance (8.5 - 9.5)</h3>
<p>Modern metropolitan lifestyles, characterized by processed foods, environmental stress, and high caffeine intake, can tilt the body toward mild acidosis. Ionized alkaline water provides essential bicarbonate ions and ionic calcium to assist your natural homeostasis.</p>
<h3>2. Negative Oxidation Reduction Potential (-ORP)</h3>
<p>VELORA Pure Ionized Alkaline Water is loaded with active molecular hydrogen, giving it strong antioxidant potential. Free radicals generated by pollution and physical exertion are safely neutralized at the mitochondrial level.</p>
<h3>3. Micro-Clustering for Faster Absorption</h3>
<p>Through state-of-the-art electrolysis, water molecule clusters are reduced from 15-20 molecules down to 5-6 molecules. This allows rapid intracellular hydration without that bloated, heavy feeling during workouts or meetings.</p>',
                'is_published' => true,
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Why Five-Star Hotels and Luxury Banquets Are Upgrading Their Water Standards',
                'slug' => 'why-luxury-hotels-are-upgrading-water-standards',
                'category' => 'Industry & B2B',
                'author_name' => 'Velora Pure Editorial',
                'excerpt' => 'From fine dining clarity to VIP corporate conferences, discover why premier hospitality brands rely on specialized 250ml petite banquet bottles.',
                'content' => '<h2>The Unspoken Standard in Luxury Hospitality</h2>
<p>Guest perception in high-end hospitality hinges on meticulous sensory details. From the weight of the glassware to the neutrality of table water during wine tastings, water is no longer merely a refreshment—it is an emblem of brand prestige.</p>
<h3>Aesthetic Banquet Formats</h3>
<p>Traditional bulky bottles clutter formal dining tables. The VELORA Pure 250 ML Petite Banquet bottle was created specifically to harmonize with fine cutlery, silver service, and executive boardroom presentations.</p>
<h3>Odorless, Neutral TDS Composition</h3>
<p>Culinary chefs know that high heavy-mineral waters distort delicate sauces and teas. Velora Pure maintains strict 8-stage purification to achieve ultra-pure neutral taste profile that complements cuisine rather than competing with it.</p>',
                'is_published' => true,
                'published_at' => now()->subDays(5),
            ],
            [
                'title' => '8-Stage Purification: How International Standards Protect Corporate Workplaces',
                'slug' => '8-stage-purification-protects-corporate-workplaces',
                'category' => 'Water Quality',
                'author_name' => 'Water Quality Engineering Team',
                'excerpt' => 'A behind-the-scenes look at Multi-Grade Sand Filtration, Micron Polishing, Reverse Osmosis, and Ozonation in professional water packaging.',
                'content' => '<h2>Purity You Can Measure in Microns</h2>
<p>Commercial workspace productivity directly correlates with team wellness and absenteeism. Contaminated or poorly filtered tap water harbors dissolved microbial cysts and heavy trace metals that impair cognitive stamina.</p>
<h3>The Velora Purification Protocol</h3>
<ul>
    <li><strong>Dual Sand & Carbon Bed:</strong> Traps particulate matter and eliminates residual chloramines, organic odors, and pesticides.</li>
    <li><strong>High-Pressure Reverse Osmosis (RO):</strong> Removes 99.8% of dissolved solids, arsenic, and nitrates.</li>
    <li><strong>Ultraviolet Sterilization:</strong> Destroys bacteria and viral DNA without thermal degradation.</li>
    <li><strong>Ozonation:</strong> Ensures zero microbial regeneration inside the hermetically sealed bottles until opened.</li>
</ul>
<p>Switching your enterprise supply to certified 20L dispensers guarantees zero-downtime health security for your workforce.</p>',
                'is_published' => true,
                'published_at' => now()->subDays(9),
            ],
        ];

        foreach ($posts as $postData) {
            Post::firstOrCreate(
                ['slug' => $postData['slug']],
                $postData
            );
        }
    }
}
